#![forbid(unsafe_code)]
//! A read-only HTML status module. Every host owns its HTTP listener,
//! authentication, source freshness, actions and domain-specific data.

use std::fmt::Write;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Health {
    Healthy,
    Degraded,
    Blocked,
    Unknown,
}

impl Health {
    const fn label(self) -> &'static str {
        match self {
            Self::Healthy => "HEALTHY",
            Self::Degraded => "DEGRADED",
            Self::Blocked => "BLOCKED",
            Self::Unknown => "UNKNOWN",
        }
    }

    const fn class(self) -> &'static str {
        match self {
            Self::Healthy => "healthy",
            Self::Degraded => "degraded",
            Self::Blocked => "blocked",
            Self::Unknown => "unknown",
        }
    }
}

/// Host-supplied evidence. `None` is rendered as UNKNOWN, never zero.
#[derive(Clone, Copy, Debug)]
pub struct Fact<'a> {
    pub label: &'a str,
    pub value: Option<&'a str>,
    pub note: &'a str,
}

/// A bounded host snapshot: caller chooses which facts are safe to expose.
/// This module never infers account state, positions or trading readiness.
#[derive(Clone, Copy, Debug)]
pub struct Snapshot<'a> {
    pub product: &'a str,
    pub mode: &'a str,
    pub health: Health,
    pub health_reason: &'a str,
    pub as_of: Option<&'a str>,
    pub facts: &'a [Fact<'a>],
}

/// Scoped styles usable inside a host-owned page, without global selectors.
#[must_use]
pub const fn stylesheet() -> &'static str {
    ".td-panel{border:1px solid #39404e;border-radius:9px;padding:18px;background:#151923;color:#eef1f7;font:14px system-ui,sans-serif;max-width:100%}.td-panel *{box-sizing:border-box}.td-panel h2{margin:0 0 12px;font-size:19px}.td-panel .td-meta{display:flex;gap:10px;flex-wrap:wrap;align-items:center;color:#d4dce8}.td-panel .td-state{font-weight:700;padding:4px 8px;border-radius:4px}.td-panel .td-state.healthy{background:#174f39}.td-panel .td-state.degraded{background:#604819}.td-panel .td-state.blocked{background:#67292c}.td-panel .td-state.unknown{background:#353b49}.td-panel .td-reason{margin:10px 0;color:#d4dce8;overflow-wrap:anywhere}.td-panel dl{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr));gap:8px;margin:10px 0 0}.td-panel .td-fact{min-width:0;border:1px solid #39404e;border-radius:5px;padding:9px}.td-panel dt{font-size:12px;color:#aab6c8}.td-panel dd{margin:5px 0 0;font-size:17px;overflow-wrap:anywhere}.td-panel small{display:block;color:#b7c2d2;margin-top:5px;overflow-wrap:anywhere}"
}

/// Render an escaped, read-only status panel for embedding in the host page.
/// Authentication must run in the host **before** calling this function.
#[must_use]
pub fn render_status_panel(snapshot: &Snapshot<'_>) -> String {
    let mut html =
        String::from("<section class=\"td-panel\" aria-label=\"Trading system status\"><h2>");
    escape_into(&mut html, snapshot.product);
    html.push_str("</h2><div class=\"td-meta\"><span>Mode: ");
    escape_into(&mut html, snapshot.mode);
    let _ = write!(
        html,
        "</span><span class=\"td-state {}\">{}</span><span>As of: ",
        snapshot.health.class(),
        snapshot.health.label()
    );
    if let Some(as_of) = snapshot.as_of {
        escape_into(&mut html, as_of);
    } else {
        html.push_str("UNKNOWN");
    }
    html.push_str("</span></div><p class=\"td-reason\">");
    escape_into(&mut html, snapshot.health_reason);
    html.push_str("</p><dl>");
    for fact in snapshot.facts {
        html.push_str("<div class=\"td-fact\"><dt>");
        escape_into(&mut html, fact.label);
        html.push_str("</dt><dd>");
        escape_into(&mut html, fact.value.unwrap_or("UNKNOWN"));
        html.push_str("</dd><small>");
        escape_into(&mut html, fact.note);
        html.push_str("</small></div>");
    }
    html.push_str("</dl></section>");
    html
}

/// Standalone page for a host's authenticated GET route. No JavaScript,
/// cookies, web controls or order submission are generated by this module.
#[must_use]
pub fn render_document(snapshot: &Snapshot<'_>) -> String {
    let mut html = String::from(
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>",
    );
    escape_into(&mut html, snapshot.product);
    html.push_str(" — status</title><style>");
    html.push_str(stylesheet());
    html.push_str("</style></head><body style=\"margin:20px;background:#0d1016;color:#eef1f7\">");
    html.push_str(&render_status_panel(snapshot));
    html.push_str("</body></html>");
    html
}

fn escape_into(html: &mut String, text: &str) {
    for ch in text.chars() {
        match ch {
            '&' => html.push_str("&amp;"),
            '<' => html.push_str("&lt;"),
            '>' => html.push_str("&gt;"),
            '"' => html.push_str("&quot;"),
            '\'' => html.push_str("&#39;"),
            _ => html.push(ch),
        }
    }
}
